apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: xvjm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xvjm
    app.kubernetes.io/part-of: byoc-app-bpja
  name: xvjm
spec:
  rules:
  - host: xvjm-byoc-gopr-tenant.apps.aef3053cbbc79a4e5ee4.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: xvjm
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
