apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: xvjm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xvjm
    app.kubernetes.io/part-of: byoc-app-bpja
  name: xvjm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: xvjm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: xvjm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-gopr-tenant/byoc-app-bpja/xvjm@sha256:8a4ea7c5517d2b404877ed7d6a5371636b0d9d860dd3cd4021f6791ed8935657
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
